[project]
name = "personal-time-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # App-specific dependencies (common deps inherited from workspace root)
    "openai>=2.1.0",
    "pandoc>=2.4",
]
