import os

from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
client = OpenAI(
    api_key=os.getenv("INCEPTION_API_KEY"),
    base_url="https://api.inceptionlabs.ai/v1"
)

response = client.chat.completions.create(
    model="mercury-coder-small",
    messages=[{"role": "user", "content": """**Instructions:**


It is essential that every significant claim of novel advantage for diffusion models be backed with a citation.

1. **Introduction:**
   - Briefly introduce the concept of diffusion models in the context of text generation.
   - Explain the current state of AI-generated text and the challenges in achieving high-quality output.

2. **Technical Overview of Diffusion Models:**
   - Describe the architecture of diffusion models, including how they generate text through a diffusion process.
   - Highlight the key advantages of diffusion models, such as parallelism, control over output, and the ability to generate text that is more coherent and contextually relevant.

3. **Comparison with Traditional Models:**
   - Compare diffusion models with traditional text generation models (e.g., auto-regressive models, recurrent neural networks).
   - Discuss the specific areas where diffusion models outperform traditional models, such as speed, efficiency, and the quality of the generated text.

4. **Case Study: AI-Generated Books:**
   - Provide a detailed case study of how diffusion models can be used to generate high-quality AI-generated books.
   - Include examples of books or chapters generated using diffusion models and compare them with those generated using traditional models.
   - Discuss the qualitative improvements, such as better coherence, more natural language, and higher reader engagement.

5. **Evaluation Metrics:**
   - Introduce metrics used to evaluate the quality of text generated by diffusion models, such as perplexity, BLEU score, and human evaluation.
   - Present the results of these metrics for both diffusion and traditional models, highlighting the superior performance of diffusion models.

6. **Future Directions:**
   - Discuss potential future research directions and improvements for diffusion models in text generation.
   - Explore the implications of these models for the broader field of AI content creation and their potential impact on industries such as publishing, journalism, and entertainment.

7. **Conclusion:**
   - Summarize the key points and the potential of diffusion models to revolutionize text generation.
   - Emphasize the importance of continued research and development in this area.

**Bibliography:**

- **Citations:**
  - [Author, Year]. *Title of the Work*. *Journal/Book Title*, Volume, Pages.
  - [Author, Year]. *Title of the Work*. *Journal/Book Title*, Volume, Pages.
  - [Author, Year]. *Title of the Work*. *Journal/Book Title*, Volume, Pages.

- **Chicago Manual of Style:**
  - Follow the Chicago Manual of Style for in citations and references.

**Example References:**

- Kingma, D. P., & Welling, M. (2013). Auto-encoding variational Bayes. *arXiv preprint arXiv:1312.6114*.
- Ho, J., Ermon, S., Kuleshov, G., Goyal, A., Grover, A., &rules,.. (2021). Denoising diffusion probabilistic models. *arXiv preprint arXiv:2006.11239*.
- Kuleshov, G., Ermon, S., Grover, A., & Ho, J. (2021). Diffusion models beat GANs on image synthesis. *arXiv preprint arXiv:2105.05233*.

This prompt is designed to provide a comprehensive and detailed exploration of how diffusion models can achieve superior quality improvements in text generation, particularly in the context of AI-generated books.


"""
               }],
    max_tokens=8000
)
print(response.choices[0].message.content)