# json with list of dicts

import json

import pandas as pd

cmw = {
    "current metadata values": [
        "format",
        "title",
        "author",
        "subject",
        "keywords",
        "creator",
        "producer",
        "creationDate",
        "modDate",
        "trapped",
        "encryption",
        "pageresizingneeded",
        "text_extractableness",
        "metadata_extractableness",
        "deduped_keywords",
        "alpha_sorted_deduped_keywords",
        "deduped_keywords_with_scores",
        "extractive_summary",
        "custom synopsis",
        "submit synopsis",
        "word length extracted pages",
        "pagecount",
        "catalog_titles",
        "Similar Titles Research",
        "exactmatch",
        "caseinsensitivematch",
        "catalog_titles_found",
        "catalog_description",
        "Suggested Titles",
        "Book Description",
        "Bibliographic Keyword Phrases",
        "Recommended BISAC Categories",
        "Book Cover Blurb",
        "Foreword",
    ]
}
KDPreq = {
    "KDP required fields": [
        "languages",
        "title",
        "Suggested Titles",
        "Suggested Subtitles",
        "Series Info",
        "author",
        "contributors",
        "AI contributors",
        "Book Cover Blurb",
        "Book Description",
        "Publishing Rights",
        "Keywords",
        "Recommended BISAC Categories",
        "ISBN-13",
        "Publication Date",
        "Binding",
        "Color",
        "Interior Trim Size",
        "Page Count",
        "Bleed Settings",
        "Cover Finish",
        "Path to Final Interior PDF",
        "Path to Final Cover PDF",
        "Barcode Source",
        "Printing Cost USD",
        "Territories Dictionary",
        "Primary Marketplace",
        "Marketplace Info Dictionaries",
        "Terms and Conditions",
    ]
}
LSIreq = {
    "LSI required fields": [
        "title",
        "Suggested Titles",
        "Suggested Subtitles",
        "languages",
        "ISBN-13",
        "Publishing Rights",
        "Series Name",
        "Series Number",
        "Edition Name",
        "Edition Number",
        "author dictionaries",
        "contributor dictionaries",
        "AI contributor dictionaries",
        "Imprint",
        "Recommended BISAC Categories",
        "Audience Type",
        "Regional Subject",
        "Thema Subjects",
        "Thema Qualifiers",
        "Table of Contents",
        "Review Quotes",
        "Full Description",
        "Keywords",
        "Short Description",
        "Binding",
        "Color",
        "Interior Trim Size",
        "Page Count",
        "Bleed Settings",
        "Cover Finish",
        "Marketplace Info Dictionaries",
        "Enable Look Inside the Book",
        "Espresso",
        "Publication Date",
        "On-Sale Date",
        "Path to Final Interior PDF",
        "Path to Final Cover PDF",
    ]
}
LSI_ACS_header = {
    "LSI ACS header fields": [
        "Lightning Source Account #",
        "Lightning Source Contact",
        "metadata contact dictionary",
        "pub comp contact dictionaries",
        "proof contact dictionaries",
    ]
}
LSI_ACS_req = {
    "LSI ACS required fields": [
        "Parent ISBN",
        "ISBN or SKU",
        "Rendition / Booktype",
        "Title",
        "Publisher",
        "Imprint",
        "Cover / Jacket Submission Method",
        "Text Block Submission Method",
        "Contributor One",
        "Contributor One Role (defaulted if blank)",
        "US Suggested List Price",
        "US Wholesale Discount (%)",
        "UK Suggested List Price",
        "UK Wholesale Discount (%)",
        '"Custom Trim Width (inches)"',
        '"Custom Trim Height (Length) (inches)"',
        "Reserved",
        "Reserved",
        "Reserved",
        "Reserved",
        "Reserved",
        "Marketing Image",
        "Pages",
        "Pub Date",
        "Street Date",
        '"Territorial Rights"',
        "Contributor Two",
        "Contributor Two Role (defaulted if blank)",
        "Contributor Three",
        "Contributor Three Role (defaulted if blank)",
        "Edition Number",
        "Edition Description",
        "Jacket Path / Filename",
        "Interior Path / Filename",
        "Cover Path / Filename",
        '"Annotation/Summary)"',
        "Reserved (SpecialInstructions)",
        "LSI Special Category (please consult LSI before using",
        "Stamped Text LEFT",
        "Stamped Text CENTER",
        "Stamped Text RIGHT",
        "Order Type Eligibility (optional / defaulted)",
        "Returnable",
        "BISAC Subject",
        "Language Code",
        "LSI FlexField1 (please consult LSI before using)",
        "LSI FlexField2 (please consult LSI before using)",
        "LSI FlexField3 (please consult LSI before using)",
        "LSI FlexField4 (please consult LSI before using)",
        "LSI FlexField5 (please consult LSI before using)",
        "Alt Currency 3 Suggested List Price ",
        "Alt Currency 3 Wholesale Discount% ",
        "BISAC Subject #2",
        "BISAC Subject #3",
        "Publisher Reference ID",
        "Alt Currency 4 Suggested List Price ",
        "Alt Currency 4 Wholesale Discount% ",
        "Carton Pack Quantity",
        "Contributor One BIO",
        "Contributor One Affiliations",
        "Contributor One Professional Position",
        "Contributor One Location",
        "Contributor One Location Type Code",
        "Contributor One Prior Work",
        "Keywords",
        "Thema Subject 1",
        "Thema Subject 2",
        "Thema Subject 3",
        "Regional Subjects",
        "Audience",
        "Min Age",
        "Max Age",
        "Min Grade",
        "Max Grade",
        "Short Description",
        "Table of Contents",
        "Review Quote(s)",
        "# Illustrations",
        "Illustration Notes",
        "Series Name",
        "# in Series",
    ]
}
LSICC = {
    "LSI_contributor_role_codes": {
        "0": "Text by (Art/Photo Books)",
        "1": "Preface by",
        "2": "Prologue by",
        "3": "Produced by",
        "4": "Read by",
        "5": "Retold by",
        "6": "Revised by",
        "7": "Selected by",
        "8": "Summary by",
        "9": "Supplement by",
        "@": "Other",
        "A": "Author",
        "AA": "With",
        "AG": "Arranged by",
        "AR": "As Recorded by",
        "B": "Abridged by",
        "BP": "Based on a Play by",
        "BV": "Based on a Book by",
        "C": "Adapted by",
        "CD": "Conducted by",
        "CP": "Composer",
        "D": "Afterword by",
        "DT": "Director",
        "E": "Editor",
        "ES": "Essay by",
        "F": "Annotations by",
        "FT": "Featuring",
        "G": "As Told to",
        "H": "As Told by",
        "I": "Illustrator",
        "J": "Contribution by",
        "JA": "Joint Author",
        "K": "Commentaries by",
        "L": "Compiled by",
        "M": "Created by",
        "MB": "Manufactured by",
        "MP": "As Made Popular by",
        "N": "Concept by",
        "O": "Designed by",
        "P": "Photographer",
        "PB": "Performed by",
        "PR": "Prepared by",
        "Q": "Epilogue by",
        "R": "Experiments by",
        "RB": "Recorded by",
        "S": "Footnotes by",
        "SB": "Screenplay by",
        "SO": "Soloist",
        "T": "Translator",
        "U": "Foreword by",
        "V": "Introduction by",
        "VB": "Vocal by",
        "W": "Memoir by",
        "WL": "Worship Leader",
        "X": "Author/Contributor Not Applica",
        "Y": "Narrated by",
        "Z": "Noted by ",
    }
}

bookcodes_df = pd.read_excel("resources/data_tables_in_csv_or_excel/LSI_booktype_codes.xlsx")
bookcodes = bookcodes_df.to_dict(orient="records")

data = [cmw, KDPreq, LSIreq, LSI_ACS_header, LSI_ACS_req, LSICC, bookcodes]


# save list as json
with open('resources/json/data.json', 'w') as outfile:
    json.dump(data, outfile)
