name: Deploy to Production

on:
  push:
    branches:
      - clean-production
  workflow_dispatch:

env:
  REMOTE_HOST: 34.172.181.254
  REMOTE_USER: wfzimmerman
  REMOTE_PATH: /home/wfzimmerman/xcu_my_apps

jobs:
  deploy:
    name: Deploy to GCP Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        env:
          SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
        run: |
          set -e
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts

          echo "Connecting to remote server..."
          ssh -i ~/.ssh/id_ed25519 $REMOTE_USER@$REMOTE_HOST << 'ENDSSH'
            set -e
            echo "Current directory: $(pwd)"
            cd /home/wfzimmerman/xcu_my_apps || { echo "Failed to cd to app directory"; exit 1; }

            echo "Git status before pull:"
            git status

            echo "Pulling latest code..."
            git pull origin clean-production || { echo "Git pull failed"; exit 1; }

            echo "Checking if service exists..."
            systemctl status codexes-factory.service --no-pager || echo "Service may not exist"

            echo "Restarting service..."
            sudo systemctl restart codexes-factory.service || { echo "Service restart failed"; exit 1; }

            echo "Service status after restart:"
            sudo systemctl status codexes-factory.service --no-pager

            echo "✅ Deployment successful!"
          ENDSSH
