name: Deploy to Production

on:
  push:
    branches:
      - clean-production
  workflow_dispatch:

env:
  REMOTE_HOST: 34.172.181.254
  REMOTE_USER: wfzimmerman
  REMOTE_PATH: /home/wfzimmerman/xcu_my_apps

jobs:
  deploy:
    name: Deploy to GCP Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        env:
          SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts
          
          ssh -i ~/.ssh/id_ed25519 $REMOTE_USER@$REMOTE_HOST "cd $REMOTE_PATH && git pull origin clean-production && sudo systemctl restart codexes-factory.service"
